name: Do some useless stuff
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      backend_sln: "Backend/Backend.sln" 
    name: ".Net Core Build"
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: "Restore NuGet packages"
        run: dotnet restore $backend_sln
      - name: "Build solution"
        run: dotnet build $backend_sln
      - name: "Run tests"
        run: dotnet test $backend_sln
      
     
