name: Do some useless stuff
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ".Net Core Build"
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build
      
     
