name: Do some useless stuff
on:
  push:
    branches: [ master ]

jobs:
  useless_stuff:
   runs-on: ubuntu-latest
   steps:
     - name: "Checkout"
       uses: actions/checkout@master
     - name: "Setup dotnet"
     - uses: actions/setup-dotnet@v1.7.2
       with:
         dotnet-version: "3.1.x"
     - name: "Build sln"
       run: dotnet build
      
     
